artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion

  source_URL: ""

  local_data_file: data/employee_attrition.csv

  train_data_path: artifacts/data_ingestion/train.csv

  test_data_path: artifacts/data_ingestion/test.csv

  raw_data_path: artifacts/data_ingestion/raw.csv
data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  train_data_path: artifacts/data_ingestion/train.csv
